version: '3'
services:
  angular:
    image: angular
    build:
      context: .
      dockerfile: angular/Dockerfile
      args:
        - PROXY=${PROXY}
        - PROXYS=${PROXYS}
    volumes:
      - ../application/:/application
    ports:
      - "4200:4200"
networks:
  default:
    external:
      name: marvelApi
